### ISSUE TITLE
is there a way to prevent OnKeyboardEvent(event) from "interrupting" device input?

### ISSUE THREAD

**Issue by isaksc2** [Tungsteno74/pyWinhook#15]
I'm basically using the `example.py` supplied in this repo, but with a `time.sleep(1)` added at the end of  `OnKeyboardEvent(event)`. Is there any way to make it so this sleep (or any other slow code) doesnt interfere with mouse movement and normal keyboard inputs?

you can see the "issue(?)" in the gif below; when I start typing, the mouse starts lagging and I can only type 1 letter per second: 
https://i.gyazo.com/bda25fe6d8f92a8935621fb7927dc9b7.mp4

**Comment by Tungsteno74** [comment]
If I understand correctly what you want to do, given the nature of the Python interpreter and how the GIL executes the code, you should be able to do it by moving one of the two parts (the code with the call to slow() or the code that manages mouse+keyboard) in a separate thread.
Try taking a look at the Python documentation below;
https://docs.python.org/3/library/threading.html
e al seguente tutorial su come usare il modulo **threading**:
https://www.tutorialspoint.com/python/python_multithreading.htm

**Comment by Tungsteno74** [comment]
If I understood well what you want to do, given the nature of the Python interpreter and how the GIL executes the code, you should be able to do it by moving one of the two parts (the code with the call to slow() or the code that manages mouse+keyboard) in a separate thread.
Try taking a look at the Python documentation below;
https://docs.python.org/3/library/threading.html
e al seguente tutorial su come usare il modulo threading:
https://www.tutorialspoint.com/python/python_multithreading.htm

p.s.: Since it's more a question than a coding error or a feature, I'm closing this request. If there were substantial changes in the type of request, it can always be reopened.
Otherwise, if you want more clarifications, you can always continue writing in this conversation.

Cheers
